# Each route describes how an incoming URL is going to be processed by Platform.sh.
"https://www.{default}/":
    type: upstream
    upstream: "app:http"

"https://{default}/":
    type: redirect
    to: "https://www.{default}/"


"https://www.meilisearch.{default}/":
    type: upstream
    upstream: app:http

"https://meilisearch.{default}/":
    type: redirect
    to: "https://www.{default}/"
